### PR TITLE
[Automatically] Add the ability to download VTM and generate MD5

### PR DESCRIPTION
**Pull request by QSXW**
New failed clips:
  GDR_D_ERICSSON_1.bit
  ILRPL_A_Huawei_3.bit
  OLS_A_Tencent_6.bit
  OLS_B_Tencent_6.bit
  OLS_C_Tencent_6.bit
  OPI_B_Nokia_4.bit
  SPATSCAL444_A_Qualcomm_3.bit
  SPATSCAL_A_Qualcomm_4.bit
  VPS_A_INTEL_4.bit
  VPS_B_ERICSSON_2.bit
  VPS_C_ERICSSON_3.bit

New passed clips:
  APSLMCS_B_Dolby_3.bit
  MNUT_A_Nokia_4.bit

### CODE REVIEW

**Comment by QSXW** [comment]
Hi, @nuomi2021. VTM 20.2 bitstreams added. Please help review.

**Comment by nuomi2021** [comment]
Thank you for the PR.  
1. V1 has sony clips. It passed. see
https://github.com/ffvvc/tests/blob/main/conformance/passed/v1/10b422_A_Sony_5.bit

2. could we use 20.02 and use VTM20.02 instead of v3? we use v2 because it from https://www.itu.int/wftp3/av-arch/jvet-site/bitstream_exchange/VVCv2/under_test/
3. dump to yuv is slow and not needed, maybe you can try pipe "vvdec.... |md5sum"

**Comment by nuomi2021** [comment]
@QSXW  thank you for the update. 
if you save the failed file name to 1.txt, use the following commands
**cat 1.txt | xargs -I {} find -name {}**
you will find the following files exist. 
```
./conformance/passed/v1/DCI_A_Tencent_3.bit
./conformance/passed/v1/DCI_B_Tencent_3.bit
./conformance/passed/v1/LTRP_A_ERICSSON_3.bit
./conformance/passed/v1/RPL_A_ERICSSON_2.bit
./conformance/passed/v1/STILL444_B_ERICSSON_1.bit
./conformance/passed/v1/STILL_B_ERICSSON_1.bit
```

**Comment by nuomi2021** [comment]
MNUT_A_Nokia_4.bit are listed at ./conformance/failed/v1/MNUT/MNUT_A_Nokia_4.bit,
it's a cornner feature, we do not support it yet.

**Comment by nuomi2021** [comment]
> @QSXW thank you for the update. if you save the failed file name to 1.txt, use the following commands **cat 1.txt | xargs -I {} find -name {}** you will find the following files exist.
> 
> ```
> ./conformance/passed/v1/DCI_A_Tencent_3.bit
> ./conformance/passed/v1/DCI_B_Tencent_3.bit
> ./conformance/passed/v1/LTRP_A_ERICSSON_3.bit
> ./conformance/passed/v1/RPL_A_ERICSSON_2.bit
> ./conformance/passed/v1/STILL444_B_ERICSSON_1.bit
> ./conformance/passed/v1/STILL_B_ERICSSON_1.bit
> ```

@QSXW  could you help check?
thank you

**Comment by QSXW** [comment]
Sure thing. These samples provide a md5 by upper case form. We need to normalize them to lowercase before comparing with FFmpeg md5.

**Comment by QSXW** [comment]
Done. New version updated.

**Comment by nuomi2021** [comment]
thank you @QSXW

**Pull request merged**
