### PR TITLE
move more dvb files to passed

### PR DESCRIPTION
**Pull request by nuomi2021**

### CODE REVIEW

**Comment by nuomi2021** [comment]
several files' md5 are mismatched with vvdec, so I have updated them. 
Now only three files have failed.
two files have RPR, one file has Sub Pic.
@frankplow , please help reviewc

thank you

**Review by frankplow — APPROVED** [review]
LGTM.  Just ran the bitstreams through VVdeC and my results concur.  The hashes I put in are from VTM — I wonder whether it has issues with very large bitstreams judging by the ones that failed?  In any case, very good that all those we expect to pass do now 😀

**Comment by nuomi2021** [comment]
not sure, maybe it's a bug of vtm, nobody tests it with such long clips.

**Comment by nuomi2021** [comment]
>very good that all those we expect to pass do now

without your patch and help, we can't do it

**Pull request merged**
