### PR TITLE
Add fuzz bitstreams

### PR DESCRIPTION
**Pull request by frankplow**
Add a load of fuzz bitstreams I have generated, and make modifications to ffmpeg.py to enable testing these in CI.

### CODE REVIEW

**Comment by frankplow** [comment]
Some of the bitstreams behave differently when run through Python compared to directly from the command line.  For example, id:000114 segfaults when run through Python, but hangs (or passes, if https://github.com/ffvvc/FFmpeg/pull/216 is applied) when run from the command line.

@nuomi2021 Any ideas what could be causing this?

**Comment by nuomi2021** [comment]
Maybe a timing issue.
The error clips may trigger the wrong states for two threads. The two threads may modify a shared memory. Depending on different executing orders, anything may happen.

**Comment by frankplow** [comment]
@nuomi2021 Yes, makes sense.

**Comment by frankplow** [comment]
@nuomi2021 The crashes, particularly the hangs, seem to behave much more consistently with `-threads 1`.  What do you think about setting this for the fuzz bitstreams?

**Comment by nuomi2021** [comment]
@frankplow , the ci's responsibility is to capture the issue. The one who debugs the issue can check --thread 1 case.

**Comment by nuomi2021** [comment]
@frankplow, 6 clips in passed are failed. 39 clips in failed are passed.
Are they passed or failed on your machine?
thank you

fuzz/passed:
> +++++++++ report +++++++++
> segfault files:
>     id:000230,sig:11,src:008581+008757,time:1385618679,execs:607369,op:splice,rep:4.bit
>     id:000229,sig:11,src:008581+008757,time:1385616727,execs:607365,op:splice,rep:2.bit
>     id:000227,sig:11,src:008581+008757,time:1385613756,execs:607359,op:splice,rep:1.bit
>     id:000228,sig:11,src:008581+008757,time:1385616230,execs:607364,op:splice,rep:2.bit
> floating-point exception files:
>     id:000195,sig:08,src:006363+008810,time:866196442,execs:450983,op:splice,rep:6.bit
>     id:000288,sig:08,src:010527+003334,time:2420272593,execs:1057922,op:splice,rep:4.bit
> 
> total = 239, passed = 233, skipped = 0, failed = 6

fuzz/failed
> +++++++++ report +++++++++
> segfault files:
>     id:000188,sig:11,src:009350+001180,time:848789467,execs:411819,op:splice,rep:4.bit
>     id:000283,sig:11,src:011945+009166,time:1518613305,execs:994341,op:splice,rep:2.bit
>     id:000225,sig:11,src:006694+007742,time:1370497949,execs:579381,op:splice,rep:7.bit
>     id:000151,sig:11,src:006267+008133,time:704172069,execs:326411,op:splice,rep:8.bit
>     id:000164,sig:11,src:008827+008127,time:755811795,execs:335692,op:splice,rep:1.bit
>     id:000156,sig:11,src:006267+008133,time:709939501,execs:327039,op:splice,rep:11.bit
>     id:000234,sig:11,src:009578+009752,time:1417185648,execs:671515,op:splice,rep:2.bit
>     id:000269,sig:11,src:007389+009802,time:1503653714,execs:940785,op:splice,rep:4.bit
>     id:000254,sig:11,src:010602+009800,time:1475219123,execs:867410,op:splice,rep:1.bit
> panic files:
>     id:000139,sig:06,src:005637+003277,time:686739912,execs:309413,op:splice,rep:2.bit
>     id:000138,sig:06,src:005637+003277,time:686739003,execs:309411,op:splice,rep:2.bit
> 
> total = 50, passed = 39, skipped = 0, failed = 11

**Comment by frankplow** [comment]
> @frankplow, 6 clips in passed are failed. 39 clips in failed are passed. Are they passed or failed on your machine? thank you

There are some intermittently failing bitstreams in `fuzz/failed` (id:000220, id:000225, id:000151, id:000283, id:000269, maybe some more).  They fail more consistently with `-threads 1`, which is partly why I think it may be worth adding as it affects the pass/fail of the bitstream as well as the precise reason.

The following bitstreams in `fuzz/passed`:
```
    id:000195,sig:08,src:006363+008810,time:866196442,execs:450983,op:splice,rep:6.bit
    id:000208,sig:11,src:000516+009526,time:1186355437,execs:516763,op:splice,rep:3.bit
    id:000201,sig:11,src:000516+009526,time:1174468552,execs:514921,op:splice,rep:3.bit
    id:000202,sig:11,src:000516+009526,time:1175135862,execs:515025,op:splice,rep:4.bit
    id:000206,sig:11,src:000516+009526,time:1179648462,execs:515722,op:splice,rep:2.bit
    id:000212,sig:11,src:000516+009526,time:1198001240,execs:518577,op:splice,rep:3.bit
    id:000214,sig:11,src:000516+009526,time:1214227143,execs:521106,op:splice,rep:4.bit
    id:000203,sig:11,src:000516+009526,time:1176735764,execs:515271,op:splice,rep:2.bit
    id:000215,sig:11,src:000516+009526,time:1219262521,execs:521890,op:splice,rep:3.bit
    id:000288,sig:08,src:010527+003334,time:2420272593,execs:1057922,op:splice,rep:4.bit
    id:000287,sig:08,src:010527+003334,time:2420271506,execs:1057913,op:splice,rep:1.bit
```
Fail for me also, but only on my Arm machine and not on my x86 machine.  I've tried compiling without hand-written assembly and with both gcc and clang, but haven't been able to replicate the failures I see on the Arm machine.  I will move these, plus the failures from your list which don't intersect this, into `fuzz/failed`.

**Comment by nuomi2021** [comment]
id:000248,sig:11,src:009080+008633,time:1446718291,execs:774170,op:splice,rep:3.bit
has a high chance of crashing on my machine...

**Comment by nuomi2021** [comment]
could you help rebase this so I can merge it?
thank you

**Comment by nuomi2021** [comment]
thank you, frank

**Pull request merged**
